name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install TA-Lib system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y wget
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzvf ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        sudo ./configure
        sudo make
        sudo make install

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check installed packages
      run: |
        pip list

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
