name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH

    - name: Initialize Conda
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda init
      shell: bash

    - name: Create Conda environment
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda create -n myenv python=3.12 --yes
        conda activate myenv
        conda install -c conda-forge ta-lib --yes
      shell: bash

    - name: Install dependencies
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate myenv
        pip install -r requirements.txt
      shell: bash

    - name: Run tests
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate myenv
        pytest
      shell: bash
